### ISSUE TITLE
Feature: User can select a fast food franchise from a dropdown menu

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fast-Food-Finder#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select from a list of fast food franchises (McDonald's, Taco Bell, and Chipotle.  Maybe add Burger King, Del Taco, Carl's Jr., Subway, Jersey Mike's, and Wienerschnitzel, if it's manageable) via a dropdown menu.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to tap (mobile) or click (desktop/laptop) on a dropdown menu towards the top of the page; and this should show a list of all the available fast food franchises the user can choose from.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20695764/171062858-3e81ee3b-9533-4b58-97fe-b98cb279276b.png)
![image](https://user-images.githubusercontent.com/20695764/171063074-c3e00deb-e351-4f5c-b459-ba84966f02c9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to create a dropdown menu of fast-food franchises

### 🧑‍⚕️ Clean Up

- [x] Add background image.
- [x] Position dropdown menu towards the top-left of the page.
- [x] Add main header.
- [x] Add a "Home" button to the left of the dropdown menu on the same row.
- [x] Create div to hold map
- [x] Position map div to take up most of the page (like in the wireframe).
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
