### ISSUE TITLE
Feature: User can choose to use their current location by clicking on an icon

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fast-Food-Finder#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose to use their current location by clicking on a marker icon towards the top right.  If the user allows the app to locate him/herself, the user's current location will be shown on the map with a marker icon.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user wants to use their current location to locate themselves on the map, the user may click on a marker icon towards the top right portion of the page.  If the user clicks on the icon, a modal will appear asking the user for confirmation.  If the user confirms, their location will be shown with a marker on the map.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20695764/171063504-280e1b56-3d4c-401b-a2f5-b28d0687917a.png)
![image](https://user-images.githubusercontent.com/20695764/171063529-7e212ba2-cfe0-42ca-90c3-fe21b85aecbe.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to add a map to the `div` reserved for the map.
- [x] Update a component to create a marker icon that enables geolocation when clicked

### 🧑‍⚕️ Clean Up

- [x] Create Google map.
- [x] Add said Google map to the `div` reserved for the map.
- [x] Create marker icon and place it on the far right side of the row containing the "Home" button and dropdown menu.
- [x] Make said marker icon functional so that it enables the Geolocation API to locate the user.
- [x] If user clicks on the marker icon, a modal should appear asking the user for permission to use the device's location
- [x] If user allows the app to retrieve the user's location, user's current location will be shown on the map with a marker icon.
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
