### ISSUE TITLE
Feature: User can view added comment(s) on "favorited" entry

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fast-Food-Finder#20]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the comment(s) that were added via the modal on the selected entry. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After inputing a comment and clicking on the 'Add Comment' button of the 'Add Comment' modal, the user will be able to view the new comment on the selected entry.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20695764/176092760-8c30c5ba-fb2e-4813-859b-e89f489dc3cc.png)
![image](https://user-images.githubusercontent.com/20695764/176092985-8b0a0cd8-9ec6-4a03-9efc-b8a1b567e1c3.png)
![image](https://user-images.githubusercontent.com/20695764/176092813-9f18789a-d3fc-4172-800b-88c0de01e1d5.png)
![image](https://user-images.githubusercontent.com/20695764/176093043-0ef98349-a777-4613-b99f-b657b06c772c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to GET comment(s) added by the user.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update component to make a fetch call to GET the comment added by the user and add it to the selected entry.
- [x] Update component to add the comment to proper space of the entry when the user clicks on the 'Confirm' button of the modal.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
