### ISSUE TITLE
Feature: User can see the nearest locations of the selected fast-food franchise on the map

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fast-Food-Finder#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the nearest locations of the selected fast-food franchise based on the user's location and the zoom level of the map.  If the user doesn't enable GPS from their device, the user can see the locations of the selected fast-food franchise on the map based on the map's position and zoom level.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user enables GPS from their device, the map will show the user the nearest locations of the fast-food franchise he/she selected from the dropdown menu.  If the user doesn't allow GPS from their device, the user will see the locations of the selected fast-food franchise based on the current position and zoom level of the map on the screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20695764/171070825-c3b4f05e-9a6b-433f-a86b-881a10165b99.png)
![image](https://user-images.githubusercontent.com/20695764/171070868-7e261832-7262-4e18-b57d-93134684e073.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to set up database.
- [x] Update `data.sql` to insert any "dummy" data into database that may be needed to start functionality.

### ☁️ Server

- [x] Update `server/index.js` to GET restaurant locations by querying Google Places database for locations based on franchise type and user's location/position of the map.
- [x] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [x] Update map component to be functional so that when a list item/link is clicked, it gathers the restaurant locations  and plots them on the map with icons.

### 🧑‍⚕️ Clean Up

- [x] GET restaurant locations data from Google Places API database when a list item is clicked from dropdown menu.
- [x] Plot restaurant locations of selected fast-food franchise on map with icons.
- [x] If user clicks on different option from dropdown menu, make sure previous icons on map are cleared.
- [x] Make sure that if user moves the map, the center latitude and longitude properties are adjusted on state.
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
