### ISSUE TITLE
Feature: User can click on a fast-food location on the map and a pop-up will appear with the location's general information

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fast-Food-Finder#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on a plotted fast-food location marked with an icon on the map and a pop-up will appear with the location's general information such as its name and address.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user clicks on an icon on the map for a fast-food location, a pop-up will appear with that location's general information such as its name and address and a button towards the bottom labeled "Add to Favorites".

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20695764/172686837-5113e2f8-c12b-4083-8493-cc823808f1d8.png)
![image](https://user-images.githubusercontent.com/20695764/172687426-41fe13f6-7ee8-4d32-9fc6-673c7b38ee1e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update component to make icons on the map clickable so that when the user clicks on one of them, a pop-up appears with general information about the location.  Also, add an "Add to Favorites" button towards the bottom of the popup.

### 🧑‍⚕️ Clean Up

- [x] Make icons on map clickable so that a popup appears with general information, such as the name of the franchise and the location's address.
- [x] Add an "Add to Favorites" button towards the bottom of the popup.
- [x] Make sure that if the user clicks on another icon, the previously selected icon's popup disappears and the newly selected icon's popup appears.
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
