### ISSUE TITLE
Feature: User can register for an account

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fast-Food-Finder#41]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can register/sign-up for an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user wants to sign-up for an account, the user can click on the 'Register' button at the right side of the second row (mobile version) or the top-right of the screen (desktop version).
The user will be taken to the 'Register' page and will be prompted to create a username and password.  
After the user has entered this information and the user clicks the 'Create an Account' button, the user will be taken back to the 'Home' page and 'Sign-in' and 'Register' buttons will be replaced with a 'Sign-out' button.
A 'welcome [username]' message will appear on the 'Home' page.
User will be able to sign-out by clicking the 'Sign-out' button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20695764/190000136-68f183be-11ee-491d-a7e3-0c2b77015a9f.png)
![image](https://user-images.githubusercontent.com/20695764/190000640-1c8c4ae1-5091-44ec-a97e-7b91765ccbb5.png)
![image](https://user-images.githubusercontent.com/20695764/189739529-0716b0de-39e5-436b-a69c-dbf36d5696f0.png)
![image](https://user-images.githubusercontent.com/20695764/190000267-589e66f9-6ab6-46f3-a4dc-15f5c9741eec.png)
![image](https://user-images.githubusercontent.com/20695764/190000700-2fecc992-5ec6-4cae-98a5-5f8fe902f90a.png)
![image](https://user-images.githubusercontent.com/20695764/189739789-8f740b50-fbeb-4e89-b9b1-64dd057dc52a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to store usernames and passwords
- [x] Update `schema.sql` to keep user-created entries and comments separated from other users.
- [x] Update `schema.sql` to keep a `guest` username and an associated password for users without an account (or those who don't want to sign up for one).

### ☁️ Server

- [x] Update `server/index.js` to GET entries and comments entered by a signed-in user.
- [x] Update `server/index.js` to POST entries and comments entered by a signed-in user.
- [x] Update `server/index.js` to PUT comments entered by a signed-in user.
- [x] Update `server/index.js` to allow a signed-in user to DELETE entries and comments.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to allow the user to register for an account ('Register' button).
- [x] Create a component to allow the user to sign-out ('Sign-out' button).
- [x] Create a page that allows the user to sign-up for an account.
- [x] Update home page to show 'Register' button.
- [x] Update home page to show 'Sign-out' button when user is signed-in.
- [x] Update home page to show a 'Welcome [username]' message when the user is signed-in.
- [x] Update home page to show a 'Welcome Guest!' message when the user is signed-in as 'Guest'.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
