### ISSUE TITLE
Feature: User can sign in.

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fast-Food-Finder#42]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in and sign out.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking a 'Sign-in' button on the home page will take the user to the 'Sign-in' page.  
In a modal, the user will be prompted for the username and password.  
If there is a username and password match in the database, the can sign in by clicking the 'Sign-in' button 
of the 'Sign-in' page.
The user will be taken to the home page with the 'Sign-in' and 'Register' buttons replaced with a 'Sign-out' button.
By clicking the 'Sign-out' button, the user will be able to sign out.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20695764/189999421-48ed5030-bc56-419f-9118-c0074e92a806.png)
![image](https://user-images.githubusercontent.com/20695764/189776040-b578132d-f65f-4e4d-8f7a-2f51d4673cd6.png)
![image](https://user-images.githubusercontent.com/20695764/189999488-44c81299-5f42-4abc-9326-e0788b4e951d.png)
![image](https://user-images.githubusercontent.com/20695764/189999744-b01b63f3-68a3-4748-b499-dd73f5a89de6.png)
![image](https://user-images.githubusercontent.com/20695764/189776065-6c96bc27-f5e5-44dd-ae53-f917937d489f.png)
![image](https://user-images.githubusercontent.com/20695764/189999822-3cea1194-58da-4902-8d18-e8b9f2768d49.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to GET the username and password entered by the user.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to create a 'Sign-in' button.
- [x] Update component to take the user to the 'Sign-in' page when the user clicks the 'Sign-in' button.
- [x] Create a 'Sign-in' page.
- [x] Update 'Sign-in' page so that when the user clicks the 'Sign-in' button of said page, the user is taken to the home page, which is also updated to show that the user is signed-in.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
