### ISSUE TITLE
Feature: User can manually enter an address in an input field

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fast-Food-Finder#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can manually enter an address in an input field rather than use their device's location.  The map will center itself based on the address provided by the user; and the application will locate the nearest fast-food restaurant locations based on this user-input.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user doesn't want to enable geolocation services from his/her device, the user may manually enter an address in a search box towards the top center of the page.  The map will re-position and center itself based on the address provided by the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20695764/172769755-f7c60536-ab0f-4921-9e01-4e9dc1ca9869.png)
![image](https://user-images.githubusercontent.com/20695764/172769785-339f6fdf-9ed6-4b65-8472-5cf9bb67cf36.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update component to create and position search box
- [x] Update component to take address entered into search box and convert it to latitude and longitude measurements
- [x] Update component to use new center coordinate measurements to center map and/or locate selected fast-food franchise.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
