### ISSUE TITLE
Feature: User can "favorite" a location

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fast-Food-Finder#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can "favorite" a location by clicking on the "Add to Favorites" button towards the bottom of the popup that appears when the user selects a location on the map.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to add a specific fast-food location to the "Favorites" view by clicking on the "Add to Favorites" button that is present towards the bottom of the popup that appears when the user clicks on a location on the map.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20695764/174515163-e49b4eb3-a093-4a69-873e-8e8c081ed33d.png)
![image](https://user-images.githubusercontent.com/20695764/174514995-1dddbfed-00b9-4336-a2e3-3bfcf158f7ab.png)
![image](https://user-images.githubusercontent.com/20695764/174515135-83bbd1b4-f4b7-4e3a-8c2c-517547af04d7.png)
![image](https://user-images.githubusercontent.com/20695764/174515051-faeb1c3e-7957-4598-9614-7c7804a5a40a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to get rid of lat, lng, and logoUrl columns.

### ☁️ Server

- [x] Update `server/index.js` to POST restaurant name, address, and googlePlaceId data.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update a component to create an entry box for a "favorited" location.
- [x] Update component to make the "Add to Favorites" button functional so that an entry box is created with that particular location's information placed in their respective sections within said entry box.
- [x] Update component to place the newly created entry box in the "Favorites" view.
- [x] Update component to allow user to view the "Favorites" page.
- [x] Update component to keep "favorited" entries stay on "Favorites" view page after refresh.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
